name: neural_prophet_env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  
  # Computation
  - numpy
  - pandas
  - pytorch
  - pystan
  - fbprophet
  - statsmodels
  
  # Plotting
  - matplotlib

  # Debugging
  - jupyter
  - pylint
  - rope
  - black
  - tqdm

  - pip:
    - neuralprophet
