name: nba_env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  
  # Computation
  - numpy
  - pandas
  - bs4
  - html5lib


  # Plotting
  - matplotlib
  - hvplot

  # Debugging
  - jupyter
  - pylint
  - rope
  - black
