name: nba_analysis_env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  
  # Computation
  - numpy
  - pandas
  - bs4
  - html5lib

  # Plotting
  - matplotlib

  # Debugging
  - jupyter
  - pylint
  - rope
  - black
  - kedro

  - pip:
    - kedro-viz
    - "kedro[pandas.ParquetDataSet]"
