name: causal_inf_env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  
  # Computation
  - numpy
  - pandas
  - 'polars[all]'
  - scikit-learn
  - statsmodels
  - dowhy

  # Plotting
  - matplotlib
  - seaborn

  # Debugging
  - jupyter
  - pylint
  - rope
  - black

  - requests

  # - pip: