name: pytorch_env
channels:
  - conda-forge
dependencies:
  - python<3.12
  - pip
  
  # Computation
  - numpy
  - pandas
  - pytorch
  - pytorch-lightning
  - scikit-learn

  # Plotting
  - matplotlib
  
  # Debugging
  - notebook
  - pylint
  - "black[jupyter]"
