name: pytorch_env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  
  # Computation
  - numpy
  - pandas
  - pytorch
  - torchvision
  - pytorch-lightning
  - scikit-learn

  # Plotting
  - matplotlib
  
  # Debugging
  - notebook
  - pylint
  - black

  pip:
    - pillow-heif
    - tensorboard