name: nba_env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  
  # Computation
  - numpy
  - pandas
  - bs4
  - html5lib
  - pytorch
  - pytorch-lightning
  - scikit-learn

  # Plotting
  - matplotlib
  - hvplot
  - seaborn
  - hiplot

  # Debugging
  - jupyter
  - pylint
  - rope
  - black