dataset:
  version: "100k"
  batch_size: 1024

model:
  architecture: "LightGCN"
  embedding_dim: 64
  n_layers: 3
  include_bias: true

training:
  epochs: 100
  learning_rate: 0.001
  loss_function: "bce"

logging:
  experiment_name: "movielens_rating_prediction"
  run_name: "lightgcn"
