dataset:
  version: "100k"  # Choose version: "100k", "1m", "25m"
  batch_size: 4096
  test_split: 0.2
  num_negatives: 4

model:
  architecture: "NeuralColabFilterNonLinear"
  embedding_dim: 10
  num_users: 943  # Will be set automatically from dataset
  num_items: 1682  # Will be set automatically from dataset

training:
  epochs: 40
  learning_rate: 0.001
  loss_function: "mse"

logging:
  experiment_name: "movielens_rating_prediction"
  run_name: "nn_colab_filter_non_linear"
