dataset:
  version: "100k"
  batch_size: 4096

model:
  architecture: "NeuralColabFilter"
  embedding_dim: 10
  num_users: 943
  num_items: 1682

training:
  epochs: 40
  learning_rate: 0.001
  loss_function: "mse"

logging:
  experiment_name: "movielens_rating_prediction"
  run_name: "nn_colab_filter_linear"
