dataset:
  version: "100k"
  batch_size: 4096
  test_split: 0.2
  num_negatives: 4

model:
  architecture: "NeuralColabFilter"
  include_bias: false
  embedding_dim: 10
  num_users: 943
  num_items: 1682

training:
  epochs: 40
  learning_rate: 0.001
  loss_function: "mse"

logging:
  experiment_name: "movielens_rating_prediction"
  run_name: "nn_colab_filter_no_bias"
