dataset:
  version: "100k"
  batch_size: 512

model:
  architecture: "RQVAE"
  hidden_dim: 256
  latent_dim: 64
  num_embeddings: 512
  num_residual_layers: 2
  commitment_cost: 0.25
  dropout: 0.5
  include_bias: true

training:
  epochs: 100
  learning_rate: 0.001
  loss_function: "bce"

logging:
  experiment_name: "movielens_rating_prediction"
  run_name: "rq_vae"
