dataset:
  version: "100k"
  batch_size: 4096
  test_split: 0.9
  num_negatives: 4

model:
  architecture: "NeuralInnerProduct"
  embedding_dim: 1
  num_users: 943
  num_items: 1682

training:
  epochs: 1
  learning_rate: 0.001
  loss_function: "mse"

logging:
  experiment_name: "movielens_rating_prediction"
  run_name: "test_run"
