name: pytorch_env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  
  # Computation
  - numpy
  - pandas
  - polars
  - pyarrow
  - pytorch
  - pytorch-lightning
  - scikit-learn

  # Plotting
  - matplotlib
  - seaborn

  # Debugging
  - jupyter
  - pylint
  - rope
  - black

  - pip:
      - lightning-bolts