dataset:
  version: "100k"
  batch_size: 1024

model:
  architecture: "DCN"
  embedding_dim: 64
  cross_layers: 3
  deep_layers: [512, 256, 128]
  dropout: 0.2

training:
  epochs: 50
  learning_rate: 0.001
  loss_function: "bce"

logging:
  experiment_name: "movielens_rating_prediction"
  run_name: "dcn"
